### ISSUE TITLE
toolbar is covered with TreeView header

### ISSUE THREAD

**Issue by cakecatz** [ignism/polymorph-ui#1]
Use this package and [toolbar](), cannot click button on toolbar.  
TreeView header has `position: fixed` and `width: 100%`.
toolbar is covered with it.
![screen shot 2015-04-02 at 8 38 57 pm](https://cloud.githubusercontent.com/assets/6136383/6963678/edf65a66-d97c-11e4-8dd9-628a69298a40.png)

**Comment by ignism** [comment]
Fixed from 1.7.16 on.
