### ISSUE TITLE
application:add-project-folder

### ISSUE THREAD

**Issue by orlin** [ignism/polymorph-ui#2]
With Atom v`0.190.0` there can be several projects opened in the same window.  Opening a second project with `polymorph-ui` on, causes the project names to be overlaid at the top, and there is no visual separation between the files of each project.  It would be awesome to get the layout repeated vertically in the "tree view" and also add ability to hide / expand each project's fs tree.

**Comment by ignism** [comment]
I didn't even know this! Just checken and it indeed looks quite bad. Actually this kinda ruins the idea behind my design.
So I came up with two solutions, the first is I already uploaded. and is updated with path 1.8.4, yet the shifting down of the panels doesn't really makes sense now. So I'm thinking of removing the margin and just align them to the top. What do you think?

**Comment by orlin** [comment]
I'm having second thoughts about opening multiple project folders.  I kind of got used to switch between windows (on a Mac) with a four-fingers-down-swipe.  If two projects have files that are named the same, which happens often - it's hard to tell which tab a file is from, without hovering over it or reading the code.    One solution is to put the project folder name of the tab that is in focus in the upper-left empty space.  It could be a repeat of the first project immediately below it, but that's perhaps acceptable.  I also notice how the One Light theme highlights a collapsed project when one of its tabs is in focus, Polymorph only highlights files.  In any case, highlighting works for sure only when the files are few enough to fit in the Tree View without scrolling.  

There is of-course the titlebar, which I simply avoid looking at, so I totally spaced it out.  I wonder if the path to the project dir could be relative, starting with the project name, or ideally have the project name precede the file name.  I guess that would be a plugin and not part of a theme.

I now kind of miss the original design...  Could a theme look different if there is one project open rather than several?  Just thinking about making the best use of the upper-left empty space.  It used to be perfect with one project per window...  So if people only work with one project at a time they would now get a degraded experience compared to the old Polymorph.
