### ISSUE TITLE
lines left of line-numbers

### ISSUE THREAD

**Issue by orlin** [ignism/polymorph-ui#3]
Polymorph is my favorite Atom UI theme.  I like it much better than One Light, my next favorite.  For many reasons, the most obvious of which being how it makes the Solarized Light syntax theme even better.  There is this one of the One Light details though that I wish Polymorph had - that is the vertical lines to the left of the line numbers - comprising unbroken / continuous / connected lines.  Could we skip the vertical spacing between the inserted / changed lines?  Adjacent lines' changes are usually part of one whole piece-of-change.  There are also lines that wrap, which should definitely feel more continuous...

I hope this wish doesn't conflict with the design's intent.

**Comment by ignism** [comment]
hey man, thanks for the input. I will look into it. You can fix it yourself by setting the font-size of the line-numbers to 1em (currently it is 0.8em with a margin of 0.1em).  come to think of it, maybe I should try padding instead of margin. I will keep you updated.

**Comment by ignism** [comment]
Adjusted the padding so that lines are continuous as of version 1.8.5

**Comment by orlin** [comment]
Perfect, thanks!
